name: ranger-server

rangerConfiguration:
  namespace: test
  zookeeper: localhost:2181

server:
  maxThreads: 128
  minThreads: 128
  applicationConnectors:
    - type: http
      port: 7080
  adminConnectors:
    - type: http
      port: 7081
  applicationContextPath: /
  requestLog:
    appenders:
      - type: console
        timeZone: IST

logging:
  level: INFO

  loggers:
    io.appform.ranger.server: DEBUG

  appenders:
    - type: console
      threshold: INFO
      timeZone: IST
      logFormat: "%(%-5level) [%date] [%thread] [%logger{0}]: %message%n"


